FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src

COPY . .
RUN dotnet restore App.sln

EXPOSE 5034
ENV ASPNETCORE_URLS=http://+:5034

CMD ["dotnet", "watch", "--project", "App.API", "run", "--urls", "http://0.0.0.0:5034"]